import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

// ใช้ฟอนต์ Inter จาก Google Fonts
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* ลิงก์ไปยัง Bootstrap CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossOrigin="anonymous"
        />
      </head>
      <body className={inter.className}>
        <div className="container mt-4">
          <h1>CIS</h1>
          <nav>
            <Link href="/" className="btn btn-link">Home</Link>{" - "}
            <Link href="/student" className="btn btn-link">Student</Link>{" - "}
            <Link href="/pokemon" className="btn btn-link">Pokemon</Link>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
